title: Xiangliru's Homepage
page-top-title: Xiangliru
top-section-bg-text: Be what you wanna be
home-subtitle: Xiangliru&ensp;|&ensp;中国石油大学（华东）
copyright-text: '&copy; Xiangliru 2023-2025. All Rights Reserved.'
